# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodListener' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodListener

# UI
  pod 'SnapKit'
  pod 'Then'

# ReactiveX
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod "RxGesture"

# API
  pod 'Alamofire'

# Decoding
  pod 'SwiftyJSON'

# Agora
#  pod 'AgoraRtcEngine_iOS'

end
