# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodListener' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodListener

# UI
  pod 'SnapKit'
  pod 'Then'
  pod 'SDWebImage', '~> 5.0'

# ReactiveX
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod "RxGesture"

# Login
  pod 'RxKakaoSDKCommon' 
  pod 'RxKakaoSDKAuth'
  pod 'RxKakaoSDKUser'

# Firebase
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

# Networking
  pod 'Moya', '~> 15.0'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'

# Decoding
  pod 'SwiftyJSON'

# Agora
  pod 'AgoraRtcEngine_iOS', '3.7.0.2'
end
